### ISSUE TITLE
Why do you have 2million lines?

### ISSUE THREAD

**Issue by fogg4444** [royalsaltmerchant/reactpractice#1]
Let's figure that out 😂

Read about .gitignore. You probably have committed your node_modules folder. Don't do that

**Comment by royalsaltmerchant** [comment]
hmm. well node_modules seems to be listed in the .gitignore file but recently I did just add a json file that contains a lot of information. that could be the culprit? Glad you brought this to my awareness, I'll investigate what is happening.

**Comment by fogg4444** [comment]
The city.json file maybe? I mean, if you need it, it's fine. How large is this file? It will also have performance implications for your page if it's too large.

**Comment by royalsaltmerchant** [comment]
41mb and it contains information for all the worlds cities that can be accessed from the openweathermap app. So when someone types in a city, if that name is equivalent to a name in city.list.json then it returns a number ID which goes into the url and fetches that info. I'm going to try to make it also have parameters for country and state.

**Comment by fogg4444** [comment]
I see. That makes sense. In a real production app you would probably not ever store 40+mb on the front end but it's fine for this. Will just load slowly

**Comment by royalsaltmerchant** [comment]
How would it be stored otherwise? Now I have another .json file with a good bit of info.
