### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by royalsaltmerchant** [royalsaltmerchant/reactpractice#10]
Not sure how to solve this issue currently.

**Comment by fogg4444** [comment]
https://stackoverflow.com/questions/42180788/how-to-use-cors-to-implement-javascript-google-places-api-request

**Comment by fogg4444** [comment]
Some good answers on this question. Looks like you need to use the JS package instead of making api calls directly

**Comment by fogg4444** [comment]
<img width="986" alt="Screen Shot 2020-10-18 at 6 25 30 PM" src="https://user-images.githubusercontent.com/10378675/96392034-9b54cc80-116f-11eb-8feb-c7dd04c34c74.png">
