### ISSUE TITLE
URL string templating / function abstraction

### ISSUE THREAD

**Issue by fogg4444** [royalsaltmerchant/reactpractice#2]
Don't write the whole url multiple times. Use string template and a function to return a formatted url. Ask me what this means if you don't get it. 

https://developers.google.com/web/updates/2015/01/ES6-Template-Strings

**Comment by royalsaltmerchant** [comment]
Hmm Okay I understand what you mean about string template, the way with the `` and the ${}. but I don't know what you mean about return a formatted url.
